# Generated by Django 5.0.4 on 2024-04-28 13:16

from django.db import migrations


def create_seller_group(apps, schema_editor):
    Group = apps.get_model("auth.Group")
    Permission = apps.get_model("auth.Permission")

    add_product_permission = Permission.objects.filter(codename="add_product")

    sellers = Group.objects.create(name="Sellers")
    sellers.permissions.set(add_product_permission)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_seller_group)
    ]
