# Generated by Django 5.0.4 on 2024-05-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_create_seller_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
