# Generated by Django 5.0.4 on 2024-05-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_image_link_alter_product_specs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
