# Generated by Django 5.0.4 on 2024-04-29 18:35

from django.db import migrations


def create_customer_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")

    content_type,_ = ContentType.objects.get_or_create(app_label="stats", model="cartitem")
    manage_cart_permission = Permission.objects.create(
        codename="manage_cartitem",
        name="Can manage cart item",
        content_type=content_type
    )

    customers = Group.objects.create(name="Customers")
    customers.permissions.add(manage_cart_permission)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('stats', '0003_rename_cart_item_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RunPython(create_customer_group)
    ]
