# Generated by Django 5.0.4 on 2024-05-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_create_customer_group'),
        ('store', '0002_create_seller_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
    ]
