# Generated by Django 5.0.4 on 2024-05-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_customer_address_alter_customer_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
