# Generated by Django 5.0.4 on 2024-05-03 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_customer_avatar'),
        ('store', '0004_category_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
        migrations.AddField(
            model_name='seller',
            name='total_products_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
